FROM alpine:3.16
LABEL maintainer="Andre Sartori <andre@aph.dev.br>"
RUN apk add --no-cache openjdk7-jre curl
WORKDIR /opt
RUN curl -O https://download.oracle.com/glassfish/3.1.2.2/release/glassfish-3.1.2.2.zip
RUN unzip glassfish-3* && rm glassfish-3*.zip
RUN ln -s glassfish3 glassfish
WORKDIR /opt/glassfish
EXPOSE 4848 8080 8181
CMD ["/opt/glassfish/bin/asadmin","start-domain","--verbose"]
